### ISSUE TITLE
500 error on /js/routing?callback=fos.Router.setData

### ISSUE THREAD

**Issue by ozzmaster** [FriendsOfSymfony/FOSJsRoutingBundle#138]
The above URL is giving me a 500 error.

The error log entry says:

PHP Fatal error:  Uncaught exception 'Symfony\Component\Serializer\Exception\UnexpectedValueException' with message 'Could not denormalize object of type Symfony\Component\Routing\RouteCollection, no supporting normalizer found.' in /~/vendor/symfony/symfony/src/Symfony/Component/Serializer/Serializer.php:281\nStack trace:\n#0 /~/vendor/symfony/symfony/src/Symfony/Component/Serializer/Serializer.php(139): Symfony\Component\Serializer\Serializer->denormalizeObject(Array, 'Symfony\Compone...', 'json', Array)\n#1 /~/vendor/symfony/symfony/src/Symfony/Component/Serializer/Serializer.php(99): Symfony\Component\Serializer\Serializer->denormalize(Array, 'Symfony\Compone...', 'json', Array)\n#2 /~/vendor/friendsofsymfony/jsrouting-bundle/FOS/JsRoutingBundle/Controller/Controller.php(90): Symfony\Component\Serialize in /~/vendor/symfony/symfony/src/Symfony/Component/Serializer/Serializer.php on line 281

What can I do to fix this?

**Comment by timwhite** [comment]
@willdurand I understand that master branches are unstable. It would be useful though to allow others to help work on your master branches. I'd love to get involved, but knowing why a branch is broken helps. This breakage has been around since 2014, it would be great to fix it and make master functional so others can be involved. Sharing a little bit of your knowledge as to why it's broken helps others pitch in and help by fixing things.
