### ISSUE TITLE
Tag new 1.5.4 release, or 1.6/2.0

### ISSUE THREAD

**Issue by weaverryan** [FriendsOfSymfony/FOSJsRoutingBundle#180]
Hi guys!

The 1.5.3 release is about 1 year old, and a branch was created by @stof when it was tagged (1.x), but new commits have been done on master. I know time is short for everyone, so I see 2 options:

1) cherry-pick some bug fixes (e.g. sha: e195b4d9505b5b9dddcc177bd7530d00ae9c3462) to 1.x, then create a simple patch release

2) Create a proper 1.6 (or 2.0) release. The diff since the last tag (https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/compare/1.5.3...master) is actually not too huge.

I know I'm not the one doing the work to make the release, so thanks in advance.

Cheers!

**Comment by stof** [comment]
the master branch contains some BC break, so we cannot release it as 1.6 (and some changes to do in the JS code for 2.0 still haven't been done, while they are a major point for 2.0.  help wanted on #181)

and we indeed messed the merge of bug fixes by applying them to master rather than 1.x. We would need to cherry-pick them to create a proper bugfix release

**Comment by stof** [comment]
Actually, something which could help is identifying which PRs merged in master after the 1.5.3 release could be backported (i.e. don't break BC). This task can be done by anyone with time

**Comment by weaverryan** [comment]
@stof done! See #182 - and thanks for the quick reply.

**Comment by stof** [comment]
1.5.4 has been tagged
