### ISSUE TITLE
Expose only accessible routes

### ISSUE THREAD

**Issue by Wirone** [FriendsOfSymfony/FOSJsRoutingBundle#188]
When using with `FOSRestBundle` we can expose whole controllers. But actions in controllers can have `@Secure` (`FrameworkExtraBundle`, `JMSSecurityExtraBundle`) annotation and it would be great to automatically ignore route (do NOT expose) when user is not allowed to use it.

It also should work when impersonating users (different set of routes for each user).

[The case](http://stackoverflow.com/questions/29139332/fosjsroutingbundle-do-not-expose-secured-and-denied-routes).

**Comment by stof** [comment]
There are several issues here:

- dumped routes don't depend on the user (this would be a pain to implement when using the controller to load them, and totally impossible when dumping a static file for performance)
- security annotations may not depend on the user only but also on values of parameters in the URL (for instance, you may be allowed to edit your own blog posts but not blog posts by others)
- this would not be enough to ensure you always get accessible routes only, because you can have security checks which are not implemented using annotations but in code (and we have no way to find them)

Trying to change the url generator to provide your access control rules to your frontend will not work. You should instead make your frontend aware of the actual business rules allowing you to access an action to decide whether the button should be visible.

**Comment by Wirone** [comment]
Consider this example: user requests for articles list, it will be displayed in datatable. If user is admin, should have controls such delete, lock etc, while others should have only "view" button. I was wondering if it's possible to determine it by routes availabilty, but I understand from your answer it won't work.

It wouldn't be a problem for standard architecture, but with Angular app with one Twig view (main layout) and other Angular views (without Symfony's security context) it's not that easy. We could use Symfony controller as a proxy for those templates but we don't want it since frontend developers are not introduced enough with Twig *and* it's not good way to mix up Twig's and Angular's markup.

**Comment by stof** [comment]
@Wirone my solution would be to make the Angular app aware of whether the user is an admin or no, and showing or hiding the button based on that.

**Comment by Wirone** [comment]
Yes, it is the way we will do it - dump user info in main layout or provide API resource for that, then Angular service for handling permissions. I was wondering only if there is different (simpler) way :-)
