### ISSUE TITLE
problem with parameter `absolute`

### ISSUE THREAD

**Issue by chrisyue** [FriendsOfSymfony/FOSJsRoutingBundle#224]
I always get absolute path even if I don't set absolute path to true

**Comment by martynchamberlin** [comment]
I'm also experiencing this problem. There's no check for whether it is set to false or not. https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/master/Resources/js/router.js#L240-L246

**Comment by LittleTwoCheng** [comment]
It will force to use absolute path when the property "host" passed via fos.Router.setData(determined by request context) are different from the host defined in specified route, i.e. (host && this.getHost() !== host)

So, when using DumpCommand(fos:js-routing:dump) to prepare the fos.Router.setData call, you must correctly defined the parameters: "router.request_context.host" in config, which let the command line know your desired host(otherwise DumpCommand will always pass "host": "localhost" to fos.Router.setData call)

refs: http://stackoverflow.com/questions/24807676/fos-js-routingbundle-produces-routes-for-localhost-only#answer-26735173

**Comment by stof** [comment]
btw, the doc is warning that you need to configure the project properly for usage of the route in the CLI, with a link to the right page of the Symfony doc.
Feel free to send a PR to improve the doc if it is not clear enough
