### ISSUE TITLE
Absolute path when schemas is http and https

### ISSUE THREAD

**Issue by thomas2411** [FriendsOfSymfony/FOSJsRoutingBundle#252]
I have a problem with routes when I use schemas set for routing for both http and https.
FOSJSRoutingBundle generates a route like this:
```
https://myhost.com/admin/partner/http|https://myhost.com/admin/partner/get-new-position/26
```
instead of:
```
https://myhost.com/admin/partner/get-new-position/26
```
or
```
http://myhost.com/admin/partner/get-new-position/26
```
My host is not fixed so I cannot set it as a parameter in a route definition. How can I fix this?

**Comment by stof** [comment]
can you show your route definition ?

**Comment by stof** [comment]
OK, looking at the JS code, it does not handle scheme requirements containing alternatives (like ``http|https``., which is why it breaks. It generates the URL as ``http|https://myhost.com/admin/partner/get-new-position/26``, which is then treated as a relative URL.

If you allow both schemes, the simpler workaround is probably to remove the scheme requirement entirely.

**Comment by thomas2411** [comment]
Indeed, the simplest solution is the best :) Thank you
