### ISSUE TITLE
The route does not exist

### ISSUE THREAD

**Issue by koukouille** [FriendsOfSymfony/FOSJsRoutingBundle#271]
Hi, i just installed FOSJsRoutingBundle via composer, added the bundle in AppKernel, expose a route, dump the route, added : 
`<script src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>
<script src="{{ path('fos_js_routing_js', { callback: 'fos.Router.setData' }) }}"></script>`
in my base.html.twig and when i generate my route, in the console it appear "The route "my_route" does not exist.

For info, my route is in other routing.yml, in an other bundle but i import it in the routing by default : 
`Mybundle_route:
    resource: "@MyBundle/Resources/config/routing.yml"
    prefix: "%prefix%"`
Can you help me ?

**Comment by stof** [comment]
have you exposed the route, as explained in the doc ?

**Comment by koukouille** [comment]
I try to expose it by the 2 ways : 
directly under the route with `options : expose: true`,
in config : `fos_js_routing: routes_to_expose: [ my_route]`,
and the both meanwhile.

But i didn't expose the route of my custom routing.yml in the default routing.yml wich is : 
`Mybundle_route: resource: "@MyBundle/Resources/config/routing.yml" prefix: "%prefix%"`.

Maybe it is the probleme ?

**Comment by richard-keller** [comment]
After upgrading from Symfony 2.8 to Symfony 3.0, I experienced the same problem.

On Symfony 2.x my routes were all exposed under `fos_js_routing` > `routes_to_expose`. 
Since upgrading to Symfony 3.0, I received the same error as @koukouille. 

The fix was to go through all of my routes and manually add `options` > `expose: true` to each one, as detailed in the [documentation](https://symfony.com/doc/master/bundles/FOSJsRoutingBundle/usage.html).

However, this is a clear BC break, which I don't see documented anywhere. Any idea why this is happening?

**Comment by koukouille** [comment]
Ok thx to richard Keller.
I post his response for others :
"After upgrading symfony from 2.8 to 3.0, the fix was to go through all of routes and manually add options > expose : true to each one"

**Comment by richard-keller** [comment]
Ah heck, I deleted my comment because I didn't think it was relevant. Sorry about that.

When I was on Symfony 2.8, I stored my exposed routes in a file called `fosjsrouting.yml` file, which I then included in my `config.yml`.

When I upgraded to Symfony 3.0, the reference to `fosjsrouting.yml` disappeared from my `config.yml`, and that's when this problem started. So in my case, the only problem was actually that my routes weren't being included anywhere, since they weren't being referenced anymore in my `config.yml`. 

I have no idea how or why my `config.yml` file changed though, and how the reference to my `fosjsrouting.yml` was removed. It's possible I did this accidentally, but since I wasn't 100% sure, I removed my previous comment here. 

Glad you came right @koukouille
