### ISSUE TITLE
Using JMSi18nRoutingBundle : conflict

### ISSUE THREAD

**Issue by z3yo** [FriendsOfSymfony/FOSJsRoutingBundle#32]
Hi,

It's impossible to generate any route if you use JMSi18nRoutingBundle, routes name are prefixed depending of the user's culture.
I don't know how to fix that, maybe using culture into generate().

If I try to generate `"my_route_test"`, I got `Route doesn't exist`, trying `fos:js-routing:debug` I have : 
`en__RG__my_route_test ANY    /hello`
`fr__RG__my_route_test ANY    /bonjour`

Even passing the culture in parameter _culture I got the error.

**Comment by pinano** [comment]
I was having the same issue as @z3yo because I was loading the router this way in my base template:

```
{% javascripts output='js/routing.js'
  'bundles/fosjsrouting/js/router.js'
  'js/fos_js_routes.js' %}
  <script src="{{ asset_url }}"></script>
{% endjavascripts %}
```
However, upon examination of the docs I noticed I had forgotten to use the fos.Router.setData callback:

```
<script src="{{ path('fos_js_routing_js', {'callback': 'fos.Router.setData'}) }}"></script>
```

I placed this <script> tag right after the previous javascripts block and now I can successfully use Routing.generate('my_route') inside any js script and it works like a charm.

So please make sure you have both imported the routing script (router.js), your dumped routes (fos_js_routes.js) and you have placed the callback method right after that.

**Comment by stof** [comment]
``fos.Router.setData`` is just the JSONP callback. Taking care of exposed routes is done server-side (and the different between the controller and the command looks weird)
