### ISSUE TITLE
Problem installing jsrouting-bundle

### ISSUE THREAD

**Issue by wanwin** [FriendsOfSymfony/FOSJsRoutingBundle#394]
Hi!
I'm trying to install this bundle in my project on Windows through command prompt using `composer require friendsofsymfony/jsrouting-bundle` but everytime I try it I get the following error:

![imagen](https://user-images.githubusercontent.com/5473947/90229887-8dea3180-de10-11ea-8fe3-aa73ef6b0eed.png)

Do you know what's happening? In case it might be helpful, I'm using Symfony 5.1.2 and I have tried the same using command prompt as admin but I got the same error message.

**Comment by stof** [comment]
I would say that you have an issue with your `%PUBLIC_DIR%` in the command for the `assets:install` script. this seems invalid. It should have been replaced by the actual name of the public dir. In any case, that seems unrelated to this bundle (the error appears with this bundle, because it contains some installable assets while many other bundles don't have any). It seems to be an issue somewhere in your project (or in Flex)
