### ISSUE TITLE
3.4.0 not working with Symfony 6.4

### ISSUE THREAD

**Issue by craigh** [FriendsOfSymfony/FOSJsRoutingBundle#473]
I tried upgrading to 3.4.0 with my current work on upgrading my app to Symfony 6.4.* and am having errors in the JS console.

<img width="572" alt="Screenshot 2023-12-12 at 4 20 35 PM" src="https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/assets/350048/cdd2d9e7-fb16-42fe-be57-9683c44f9d6f">

I'm sure it is something I've done wrong, but if I downgrade to 3.3.0, then it works fine. Please let me know what else you need to help solve the issue. I am using webpack.

**Comment by ajgarlag** [comment]
I'm having the same issue. The regression was introduced in 23b8ec9fd4bebbd42ad505d76da02846ed950bcf.

**Comment by flodaq** [comment]
Same issue. Downgrade to 3.3.0 solved the issue.

**Comment by pyksid** [comment]
Same issued here too. Revert to previous version.

**Comment by ajgarlag** [comment]
@ar10642, can you review this issue? Thanks!

**Comment by ar10642** [comment]
OK maybe this doesn't work as expected, although all tests passed for me. Possibly some situation not covered by the tests. We are using Symfony 5.4 and didn't have any errors. I don't have any Symfony 6.4 projects I can try this with right now. Might need to revert?

**Comment by ajgarlag** [comment]
@ar10642, here is a reproducer with Symfony 5.4: https://github.com/ajgarlag/FOSJsRoutingBundle/blob/issue-473-reproducer/README.md

The diff between the working and failing commits is https://github.com/ajgarlag/FOSJsRoutingBundle/commit/4e83701cbf17b0b6b92b69a5c7a9fe56ba5ddf41

Hope this can help you or any other developer to fix the bug.

**Comment by tobias-93** [comment]
Hi all,

First of all, this is independent of the Symfony version as the only thing that was broken is the Webpack integration.
@ajgarlag thanks for the reproducer, that was actually of great help.
The problem was that the previous implementation of the Webpack plugin (which is a part of the bundle which is not included in the automated tests) would actually inject the generated files, but the `BannerPlugin` is only meant to prepend or append text in a built file.
I have found a fork of the original plugin which doesn't seem abandoned, and doesn't rely on the vulnerable dependency for which the original action was executed.
Please try release 3.4.1 and let me know, I myself don't use the Webpack plugin so it's hard for me to test in an actual application.

**Comment by craigh** [comment]
@tobias-93 

3.4.1 is working for me. thank you for the fix!

**Comment by tobias-93** [comment]
@craigh thanks for the feedback, closing the issue.

**Comment by ar10642** [comment]
Ok, thanks all, sorry for any problems I might have caused, I genuinely
thought it was working.

**Comment by ajgarlag** [comment]
@tobias-93 Thanks for the fix. It works fine!
